### PR TITLE
Feature/username links

### LINKED ISSUE #38: Username links
Would be cool to be able to go to the users' GH profiles when clicking on their names/avatars.

### PR DESCRIPTION
**Pull request by ANDREYDEN**
Main purpose: fix #38 

- Adds `User` model which has a `githubUrl` getter
- Adds the `username` field to the `User` model in the backend

### CODE REVIEW

**Comment by ANDREYDEN** [comment]
This turned out to be a bit deeper than I expected...

**Comment by FRFlor** [comment]
Thanks Andrii! 

Do you mind renaming the "username" column to "github_nickname" or something in line with that?  Just to make it clear what that is when someone is reading the migrations. 

Since the column is already in the users table, having the prefix "user" ends up being redundant.

**Comment by FRFlor** [comment]
Ah another thing as well @ANDREYDEN , do you mind adding this new column in a dedicated new migration? 

Since the app is already running in production, I prefer to keep track of the migrations changes using the files. 

`php artisan make:migration add_github_nickname_column_to_users_table --table=users` should create the migration

**Comment by ANDREYDEN** [comment]
I think that should be it, but check out the `WebHooksTest.php` - I was getting some inconsistent tests...
Sometimes they would throw exceptions about `id` on `SocialMob` and sometimes they would be fine. Idk if this is just my setup or just something wrong with the tests.

**Review by FRFlor — APPROVED** [review]

**Pull request merged**
